services:

  db-clients:
    image: postgres:15
    container_name: db-clients
    environment:
      POSTGRES_DB: db_clients
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"

  db-accounts:
    image: postgres:15
    container_name: db-accounts
    environment:
      POSTGRES_DB: db_accounts
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"